export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_CLEARED = 'REGISTER_CLEARED';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT'; 
export const COMPANY_LOADED ='COMPANY_LOADED'; 
export const COMPANY_ERROR ='COMPANY_ERROR'; 
export const CLEAR_COMPANY = 'CLEAR_COMPANY';
export const ROLES_LOADED = 'ROLES_LOADED';
export const ROLES_CLEARED = 'ROLES_CLEARED';
export const ROLES_ERROR = 'ROLES_ERROR';
export const USERS_LOADED = 'USERS_LOADED';
export const USERS_UPDATED = 'USERS_UPDATED';
export const USERS_READY = 'USERS_READY';
export const USERS_ERROR = 'USERS_ERROR';
export const USERS_CLEARED = 'USERS_CLEARED';
export const INVITATIONS_SENT = 'INVITATIONS_SENT';
export const INVITATIONS_CLEARED = 'INVITATIONS_CLEARED';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const PRODUCTS_FILTERED_LOADED = 'PRODUCTS_FILTERED_LOADED';
export const PRODUCT_BY_ID_LOADED = 'PRODUCT_BY_ID_LOADED';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_CLEARED = 'PRODUCTS_CLEARED';
export const PRODUCTS_ERROR = 'PRODUCTS_LOADED';
export const PRODUCTS_ACTION_SUCCESS = 'PRODUCTS_ACTION_SUCCESS';
export const PRODUCTS_ACTION_CLEARED = 'PRODUCTS_ACTION_CLEARED';




